-- seed.sql — datos de prueba (equivalentes al mock actual)

-- Salas
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Sala 1 - 3D', 10, 6);
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Sala 2', 10, 6);
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Sala 3', 10, 6);
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Sala 4', 10, 6);
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Sala 5', 10, 6);
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Sala 6', 10, 6);
INSERT INTO salas (nombre, filas, columnas_por_bloque) VALUES ('Teatro Principal', 10, 6);

-- Asientos (10 filas x 12 columnas por cada sala)
INSERT INTO asientos (id_sala, fila, columna, codigo)
SELECT s.id_sala, f.fila, c.col, f.fila || c.col::text
FROM salas s
CROSS JOIN unnest(ARRAY['A','B','C','D','E','F','G','H','I','J']) AS f(fila)
CROSS JOIN generate_series(1, 12) AS c(col);

-- Eventos (películas y shows)
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Guardianes del Multiverso', 'Acción / Ciencia Ficción', 128, 'B', 'Un equipo de héroes debe evitar el colapso de realidades paralelas.', 65.0, 'assets/posters/peli_1.jpg', 'pelicula');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Risas en la Oficina', 'Comedia', 102, 'A', 'Un empleado torpe intenta salvar la empresa el día del auditor.', 55.0, 'assets/posters/peli_2.jpg', 'pelicula');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('El Último Faro', 'Drama / Suspenso', 115, 'B15', 'Un guardafaro descubre un secreto que cambiará su pueblo para siempre.', 55.0, 'assets/posters/peli_3.jpg', 'pelicula');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Aventura Bajo el Mar', 'Animación / Familiar', 95, 'A', 'Una pequeña tortuga emprende un viaje para encontrar a su familia.', 50.0, 'assets/posters/peli_4.jpg', 'pelicula');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Noche de Terror', 'Terror', 98, 'C', 'Cinco amigos quedan atrapados en una cabaña con algo que no es humano.', 60.0, 'assets/posters/peli_5.jpg', 'pelicula');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Corazones en Ruta', 'Romance', 110, 'B', 'Dos desconocidos comparten un viaje en tren que cambia sus vidas.', 55.0, 'assets/posters/peli_6.jpg', 'pelicula');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Concierto Sinfónico de Medianoche', 'Música / Orquesta', 90, 'A', 'La orquesta local interpreta clásicos bajo un ambiente íntimo.', 120.0, 'assets/posters/show_1.jpg', 'show');
INSERT INTO eventos (titulo, genero, duracion_min, clasificacion, sinopsis, precio, poster_url, tipo) VALUES ('Stand Up: Noche de Risas', 'Comedia en vivo', 75, 'B15', 'Tres comediantes locales se suben al escenario a hacerte reír.', 95.0, 'assets/posters/show_2.jpg', 'show');

-- Funciones (evento + sala + horario)
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '14:00' FROM eventos e, salas s WHERE e.titulo = 'Guardianes del Multiverso' AND s.nombre = 'Sala 1 - 3D';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '17:30' FROM eventos e, salas s WHERE e.titulo = 'Guardianes del Multiverso' AND s.nombre = 'Sala 1 - 3D';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '21:00' FROM eventos e, salas s WHERE e.titulo = 'Guardianes del Multiverso' AND s.nombre = 'Sala 1 - 3D';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '13:00' FROM eventos e, salas s WHERE e.titulo = 'Risas en la Oficina' AND s.nombre = 'Sala 2';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '16:00' FROM eventos e, salas s WHERE e.titulo = 'Risas en la Oficina' AND s.nombre = 'Sala 2';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '19:00' FROM eventos e, salas s WHERE e.titulo = 'Risas en la Oficina' AND s.nombre = 'Sala 2';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '18:00' FROM eventos e, salas s WHERE e.titulo = 'El Último Faro' AND s.nombre = 'Sala 3';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '20:45' FROM eventos e, salas s WHERE e.titulo = 'El Último Faro' AND s.nombre = 'Sala 3';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '12:00' FROM eventos e, salas s WHERE e.titulo = 'Aventura Bajo el Mar' AND s.nombre = 'Sala 4';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '15:00' FROM eventos e, salas s WHERE e.titulo = 'Aventura Bajo el Mar' AND s.nombre = 'Sala 4';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '17:15' FROM eventos e, salas s WHERE e.titulo = 'Aventura Bajo el Mar' AND s.nombre = 'Sala 4';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '22:00' FROM eventos e, salas s WHERE e.titulo = 'Noche de Terror' AND s.nombre = 'Sala 5';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '23:30' FROM eventos e, salas s WHERE e.titulo = 'Noche de Terror' AND s.nombre = 'Sala 5';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '16:30' FROM eventos e, salas s WHERE e.titulo = 'Corazones en Ruta' AND s.nombre = 'Sala 6';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '19:45' FROM eventos e, salas s WHERE e.titulo = 'Corazones en Ruta' AND s.nombre = 'Sala 6';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '20:00' FROM eventos e, salas s WHERE e.titulo = 'Concierto Sinfónico de Medianoche' AND s.nombre = 'Teatro Principal';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '19:00' FROM eventos e, salas s WHERE e.titulo = 'Stand Up: Noche de Risas' AND s.nombre = 'Teatro Principal';
INSERT INTO funciones (id_evento, id_sala, fecha, hora) SELECT e.id_evento, s.id_sala, '2026-09-20', '21:30' FROM eventos e, salas s WHERE e.titulo = 'Stand Up: Noche de Risas' AND s.nombre = 'Teatro Principal';

-- Boletos y asientos ocupados (igual que el mock actual)
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0001', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0002', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0003', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0004', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0005', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0006', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0007', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0008', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0009', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0010', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0011', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F11' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0012', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F12' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0013', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H4' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0014', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0015', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0016', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I10' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0017', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I9' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0018', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'J1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 1 - 3D' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0019', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'J2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 1 - 3D';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0020', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B3' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0021', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B4' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0022', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C10' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0023', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C9' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0024', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0025', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0026', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0027', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0028', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0029', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0030', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0031', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0032', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H9' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0033', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I11' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 2' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0034', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I12' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 2';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0035', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0036', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A11' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0037', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A12' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0038', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0039', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0040', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0041', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0042', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0043', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F10' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0044', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F3' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0045', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F4' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0046', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F9' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0047', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 3' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0048', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 3';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0049', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0050', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0051', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'C8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0052', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0053', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E11' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0054', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E12' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0055', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0056', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0057', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0058', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 4' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0059', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 4';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0060', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0061', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0062', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0063', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0064', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E10' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0065', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E9' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0066', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0067', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0068', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'J5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0069', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'J6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 5' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0070', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'J7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 5';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0071', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0072', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0073', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0074', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'A8' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0075', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0076', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'D2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0077', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0078', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'F7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0079', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H10' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0080', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H11' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Sala 6' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0081', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'H12' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Sala 6';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0082', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B4' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0083', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0084', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0085', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'B7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0086', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E1' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0087', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E11' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0088', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E12' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0089', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'E2' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0090', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G5' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0091', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G6' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0092', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'G7' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0093', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I10' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0094', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I3' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0095', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I4' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';
WITH func AS (  SELECT f.id_funcion FROM funciones f JOIN salas s ON s.id_sala = f.id_sala   WHERE s.nombre = 'Teatro Principal' ORDER BY f.id_funcion LIMIT 1), nuevo_boleto AS (  INSERT INTO boletos (folio, id_funcion, total, qr_data)   SELECT 'SEED-0096', func.id_funcion, 0, 'seed' FROM func   RETURNING id_boleto, id_funcion) INSERT INTO boleto_asientos (id_boleto, id_asiento, id_funcion) SELECT nb.id_boleto, a.id_asiento, nb.id_funcion FROM nuevo_boleto nb JOIN asientos a ON a.codigo = 'I9' JOIN salas s2 ON s2.id_sala = a.id_sala AND s2.nombre = 'Teatro Principal';